language: python
python:
- 3.7
services:
  - docker
before_install:
- make install
- docker pull aerospike/aerospike-server
script:
- make lint-check
- docker run -d -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 aerospike/aerospike-server
- make test
